# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20170127_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Short descriptive unique name for use in urls.', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Short descriptive unique name for use in urls.', max_length=200),
        ),
    ]
