# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20170508_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_likes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
