# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_auto_20170508_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
